### ISSUE TITLE
Blocking upload : SyntaxError: Unexpected token E in JSON at position 0

### ISSUE THREAD

**Issue by davidlevy** [kbremner/grunt-dropbox#17]
Hi 

Since my upgrade to v0.1.3, I cannot upload any files, I get this error : 

```
Running "dropbox:release" (dropbox) task
Uploading to dropbox account for David Levy...
Uploading xxxx to xxx
Possibly unhandled SyntaxError: Unexpected token E in JSON at position 0
  at JSON.parse (<anonymous>:null:null)
  at parseBody (/Library/WebServer/Documents/vp/m2/w/node_modules/grunt-dropbox/lib/dropbox.js:17:17)
  at tryCatch1 (/Library/WebServer/Documents/vp/m2/w/node_modules/grunt-dropbox/node_modules/bluebird/js/main/util.js:45:21)
  at Promise$_callHandler [as _callHandler] (/Library/WebServer/Documents/vp/m2/w/node_modules/grunt-dropbox/node_modules/bluebird/js/main/promise.js:660:13)
  at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Library/WebServer/Documents/vp/m2/w/node_modules/grunt-dropbox/node_modules/bluebird/js/main/promise.js:675:18)
  at Promise$_settlePromiseAt [as _settlePromiseAt] (/Library/WebServer/Documents/vp/m2/w/node_modules/grunt-dropbox/node_modules/bluebird/js/main/promise.js:845:14)
  at Promise$_settlePromises [as _settlePromises] (/Library/WebServer/Documents/vp/m2/w/node_modules/grunt-dropbox/node_modules/bluebird/js/main/promise.js:988:14)
  at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Library/WebServer/Documents/vp/m2/w/node_modules/grunt-dropbox/node_modules/bluebird/js/main/async.js:77:12)
  at Async$consumeFunctionBuffer (/Library/WebServer/Documents/vp/m2/w/node_modules/grunt-dropbox/node_modules/bluebird/js/main/async.js:40:14)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

```
Someone could fix it ?

**Comment by kbremner** [comment]
Hi, 0.2.0 is now on NPM, can you upgrade to that version please?
That version includes #15, which added support for Dropbox's v2 API. v1 of the API was turned off on 28th September, as mentioned in that PR, which is most likely the problem.

**Comment by davidlevy** [comment]
Same same :(
Sorry I forgot to mention it was also occuring with 0.2.0 ( I upgraded in another branch )

I am using npm 4.1.2

**Comment by stevehenty** [comment]
@davidlevy perhaps a bit late, but try adding a slash to the beginning of the upload path.

**Comment by davidlevy** [comment]
I tried it @stevehenty , the uploads _works_ but then I can't file the file. I guess Dropbox gets lost with this absolute path ... 

```
            release: {
                files: {
                    '/webapp': ['<%= distDir %>vp_webapp-<%= version %>.zip']
                }
            }
```

Another idea ?

**Comment by stevehenty** [comment]
In my case the file is uploaded to `my dropbox folder`/Apps/`Name of the app`/ `upload path`

**Comment by davidlevy** [comment]
It works now with the previous commented config and making sure my `distDir` is a relative path , not starting with` ./ `
Thanks @stevehenty  !!
